Fix Linux 32-bit compilation after sysroot switch.
The roll in https://codereview.webrtc.org/1713493002/
made us start using the Chromium sysroot images for libraries instead
of system libraries. This caused Linux 32-bit builds to break with
an error like this:
../../webrtc/examples/peerconnection/client/linux/main_wnd.cc:82:46: error: missing sentinel in function call [-Werror,-Wsentinel]
      "List Items", renderer, "text", 0, NULL);
                                             ^
                                             , nullptr
/usr/include/gtk-2.0/gtk/gtktreeviewcolumn.h:128:25: note: function has been explicitly marked sentinel here
GtkTreeViewColumn      *gtk_tree_view_column_new_with_attributes (const gchar             *title,
                        ^
1 error generated.

This CL suppresses this warning to green up the bots.

TBR=niklase@webrtc.org

Review URL: https://codereview.webrtc.org/1710083003 .

Cr-Commit-Position: refs/heads/master@{#11674}