Revert of Extract iOS SDK helpers to separate target. (patchset #1 id:1 of https://codereview.webrtc.org/2852323003/ )
Reason for revert:
It is still breaking chromium trybots:

Undefined symbols for architecture x86_64:
  "base::allocator::g_replaced_default_zone", referenced from:
      base::allocator::IsAllocatorInitialized() in libbase.a(allocator_check.o)
ld: symbol(s) not found for architecture x86_64

Original issue's description:
> Reland of Extract iOS SDK helpers to separate target. (patchset #1 id:1 of https://codereview.webrtc.org/2853273002/ )
>
> Reason for revert:
> Trying to reland after: https://codereview.webrtc.org/2855103003.
>
> Original issue's description:
> > Revert of Extract iOS SDK helpers to separate target. (patchset #3 id:40001 of https://codereview.webrtc.org/2849823002/ )
> >
> > Reason for revert:
> > https://chromium.googlesource.com/external/webrtc/+/3c1e558449309be965815e1bf...
> >
> > I suspect this breaks Chrome ios.
> > https://build.chromium.org/p/tryserver.chromium.mac/builders/ios-simulator/bu...
> > https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Ftryserver.chromium.mac%2...
> >
> > Undefined symbols for architecture x86_64:
> >   "base::allocator::g_replaced_default_zone", referenced from:
> >       base::allocator::IsAllocatorInitialized() in libbase.a(allocator_check.o)
> > ld: symbol(s) not found for architecture x86_64
> > clang: error: linker command failed with exit code 1 (use -v to see invocation)
> > Traceback (most recent call last):
> >   File "../../build/toolchain/mac/linker_driver.py", line 229, in <module>
> >     Main(sys.argv)
> >   File "../../build/toolchain/mac/linker_driver.py", line 79, in Main
> >     subprocess.check_call(compiler_driver_args)
> >   File
> > "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py",
> > line 540, in check_call
> >     raise CalledProcessError(retcode, cmd)
> >
> > Original issue's description:
> > > Extract iOS SDK helpers to separate target.
> > >
> > > This will reduce the redundant objects built
> > > in Chromium when opening up test_support for the fuzzer
> > > tests.
> > >
> > > BUG=webrtc:6828
> > > NOTRY=True
> > >
> > > Review-Url: https://codereview.webrtc.org/2849823002
> > > Cr-Commit-Position: refs/heads/master@{#17972}
> > > Committed: https://chromium.googlesource.com/external/webrtc/+/3c1e558449309be965815e1bf67d2391500343ce
> >
> > TBR=mbonadei@webrtc.org,kjellander@webrtc.org
> > # Skipping CQ checks because original CL landed less than 1 days ago.
> > NOPRESUBMIT=true
> > NOTREECHECKS=true
> > NOTRY=true
> > BUG=webrtc:6828
> >
> > Review-Url: https://codereview.webrtc.org/2853273002
> > Cr-Commit-Position: refs/heads/master@{#17979}
> > Committed: https://chromium.googlesource.com/external/webrtc/+/80e230239ebcb09c6e31b6b50ca1e61ae49ef1fb
>
> TBR=kjellander@webrtc.org,perkj@webrtc.org
> # Skipping CQ checks because original CL landed less than 1 days ago.
> NOPRESUBMIT=true
> NOTREECHECKS=true
> NOTRY=true
> BUG=webrtc:6828
>
> Review-Url: https://codereview.webrtc.org/2852323003
> Cr-Commit-Position: refs/heads/master@{#17992}
> Committed: https://chromium.googlesource.com/external/webrtc/+/fafd6d850d0710e7279901dda94b67cba5996aba

TBR=kjellander@webrtc.org,perkj@webrtc.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=webrtc:6828

Review-Url: https://codereview.webrtc.org/2857953003
Cr-Commit-Position: refs/heads/master@{#17995}