Revert "Add possibility to expand strings in the autoroller."
This reverts commit bfb6124a73af8c9fb806d9798c21aa28d36b125f.

Reason for revert: Testing Autoroller notifications. I will reland this later.

Original change's description:
> Add possibility to expand strings in the autoroller.
> 
> Starting from crrev.com/c/2265498, the Chromium DEPS file has a new
> function Str(), which seems to just expand to the string it wraps.
> 
> This causes the following error:
> 
>   NameError: name 'Str' is not defined
> 
> In //tools_webrtc/autoroller/roll_deps.py.
> 
> This CL adds a way to expand the string.
> 
> No-Try: True
> Bug: None
> Change-Id: I4cdb43410edeed72b393f200314c0ee7eea9cb2a
> Reviewed-on: https://webrtc-review.googlesource.com/c/src/+/178865
> Commit-Queue: Mirko Bonadei <mbonadei@webrtc.org>
> Reviewed-by: Jeremy Leconte <jleconte@webrtc.org>
> Cr-Commit-Position: refs/heads/master@{#31661}

TBR=mbonadei@webrtc.org,jleconte@webrtc.org

Change-Id: I69f75da132d6b838b96a559712ad4c0da929021c
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: None
Reviewed-on: https://webrtc-review.googlesource.com/c/src/+/178877
Reviewed-by: Mirko Bonadei <mbonadei@webrtc.org>
Commit-Queue: Mirko Bonadei <mbonadei@webrtc.org>
Cr-Commit-Position: refs/heads/master@{#31673}