Revert "Fix circular dependency in BWE code."
This reverts commit 08279b5cf5a8412f7e946cc2bb43703e920f5855.

Reason for revert: msvc bots breaking, blocking WebRTC rolls.

Sample log:
FAILED: obj/third_party/webrtc/modules/congestion_controller/estimators/probe_bitrate_estimator.obj 
ninja -t msvc -e environment.x64 -- E:\b\c\goma_client/gomacc.exe "e:\b\c\win_toolchain\vs_files\1180cb75833ea365097e279efb2d5d7a42dee4b0\vc\tools\msvc\14.11.25503\bin\hostx64\x64/cl.exe" /nologo /showIncludes  @obj/third_party/webrtc/modules/congestion_controller/estimators/probe_bitrate_estimator.obj.rsp /c ../../third_party/webrtc/modules/congestion_controller/probe_bitrate_estimator.cc /Foobj/third_party/webrtc/modules/congestion_controller/estimators/probe_bitrate_estimator.obj /Fd"obj/third_party/webrtc/modules/congestion_controller/estimators_cc.pdb"
../../third_party/webrtc/modules/congestion_controller/probe_bitrate_estimator.cc(68): error C2220: warning treated as error - no 'object' file generated
../../third_party/webrtc/modules/congestion_controller/probe_bitrate_estimator.cc(68): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
[22699/51826] CXX obj/third_party/webrtc/modules/pacing/pacing/packet_router.obj
[22700/51826] CXX obj/third_party/webrtc/modules/remote_bitrate_estimator/remote_bitrate_estimator/aimd_rate_control.obj
[22701/51826] CXX obj/third_party/webrtc/modules/desktop_capture/desktop_capture_generic/dxgi_texture_mapping.obj
[22702/51826] CXX obj/third_party/webrtc/modules/congestion_controller/estimators/acknowledged_bitrate_estimator.obj
FAILED: obj/third_party/webrtc/modules/congestion_controller/estimators/acknowledged_bitrate_estimator.obj 
ninja -t msvc -e environment.x64 -- E:\b\c\goma_client/gomacc.exe "e:\b\c\win_toolchain\vs_files\1180cb75833ea365097e279efb2d5d7a42dee4b0\vc\tools\msvc\14.11.25503\bin\hostx64\x64/cl.exe" /nologo /showIncludes  @obj/third_party/webrtc/modules/congestion_controller/estimators/acknowledged_bitrate_estimator.obj.rsp /c ../../third_party/webrtc/modules/congestion_controller/acknowledged_bitrate_estimator.cc /Foobj/third_party/webrtc/modules/congestion_controller/estimators/acknowledged_bitrate_estimator.obj /Fd"obj/third_party/webrtc/modules/congestion_controller/estimators_cc.pdb"
../../third_party/webrtc/modules/congestion_controller/acknowledged_bitrate_estimator.cc(41): error C2220: warning treated as error - no 'object' file generated
../../third_party/webrtc/modules/congestion_controller/acknowledged_bitrate_estimator.cc(41): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data

https://logs.chromium.org/v/?s=chromium%2Fbb%2Ftryserver.chromium.win%2Fwin-msvc-dbg%2F1780%2F%2B%2Frecipes%2Fsteps%2Fcompile__with_patch_%2F0%2Fstdout


Original change's description:
> Fix circular dependency in BWE code.
> 
> Bug: webrtc:6828
> Change-Id: I531ee5dea41140f085d82641253fadb9e997a378
> Reviewed-on: https://webrtc-review.googlesource.com/34641
> Reviewed-by: Stefan Holmer <stefan@webrtc.org>
> Commit-Queue: Patrik Höglund <phoglund@webrtc.org>
> Cr-Commit-Position: refs/heads/master@{#21350}

TBR=phoglund@webrtc.org,stefan@webrtc.org

# Not skipping CQ checks because original CL landed > 1 day ago.

Bug: webrtc:6828
Change-Id: I361050942cbd1d2b344b129c8c3a4e7b6e1c02f4
Reviewed-on: https://webrtc-review.googlesource.com/35240
Reviewed-by: Olga Sharonova <olka@webrtc.org>
Commit-Queue: Olga Sharonova <olka@webrtc.org>
Cr-Commit-Position: refs/heads/master@{#21384}