Don't include <memory.h> in aligned_malloc.cc.
The inclusion of <memory.h> creates problems when building with Chromium
third_party/webrtc/rtc_base/memory/aligned_malloc.cc:13:10:
  fatal error: 'memory.h' file not found
    #include <memory.h>

It seems the code doesn't need to include <memory.h> but <cstring>.

Bug: None
Change-Id: Ib6591711aa7cfea49a2ff08321cfb3bd3689797a
Reviewed-on: https://webrtc-review.googlesource.com/c/103980
Reviewed-by: Karl Wiberg <kwiberg@webrtc.org>
Commit-Queue: Mirko Bonadei <mbonadei@webrtc.org>
Cr-Commit-Position: refs/heads/master@{#25003}